// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nehwcsdzdegsqrnergwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5laHdjc2R6ZGVnc3FybmVyZ3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Nzc5OTMsImV4cCI6MjA2NjA1Mzk5M30.xJ8kmpPDpFZALi-zfUzpLIFfxk_0aeqnrpxbljL-yiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);